document.writeln('<link href="../css/public/footer.css"  rel="stylesheet" type="text/css" />');
document.writeln('<footer>');
document.writeln('   <div class="main-w">');
document.writeln('        <div class="footer-top cleart">');
document.writeln('            <div class="pull-left">');
document.writeln('                <div class="item">');
document.writeln('                    <h3>');
document.writeln('                        <a href="../tradeHall/newProducts.html">交易大厅</a>');
document.writeln('                    </h3>');
document.writeln('                    <ul>');
document.writeln('                        <li>');
document.writeln('                            <a href="../tradeHall/newProducts.html">新品中心</a>');
document.writeln('                        </li>');
document.writeln('                        <li>');
document.writeln('                            <a href="../tradeHall/transferCenter.html">转让中心</a>');
document.writeln('                        </li>');
document.writeln('                        <li>');
document.writeln('                            <a href="../tradeHall/bidPowerStation.html">竞价电站</a>');
document.writeln('                        </li>');
document.writeln('                        <li>');
document.writeln('                            <a href="../tradeHall/fixedPowerStation.html">一口价电站</a>');
document.writeln('                        </li>');
document.writeln('                    </ul>');
document.writeln('                </div>');
document.writeln('                <div class="item">');
document.writeln('                    <h3>');
document.writeln('                        <a href="../assetCenter/rentStation.html">资产中心</a>');
document.writeln('                    </h3>');
document.writeln('                    <ul>');
document.writeln('                        <li>');
document.writeln('                            <a href="../assetCenter/rentStation.html">我租赁的电站</a>');
document.writeln('                        </li>');
document.writeln('                        <li>');
document.writeln('                            <a href="../assetCenter/investmentStation.html">我投资的电站</a>');
document.writeln('                        </li>');
document.writeln('                    </ul>');
document.writeln('                </div>');
document.writeln('                <div class="item">');
document.writeln('                    <h3>');
document.writeln('                        <a href="../personal/revenueRecord.html">个人中心</a>');
document.writeln('                    </h3>');
document.writeln('                    <ul>');
document.writeln('                        <li>');
document.writeln('                            <a href="../personal/revenueRecord.html">我的收益</a>');
document.writeln('                        </li>');
document.writeln('                        <li>');
document.writeln('                            <a href="../personal/accountSet.html">我的账户</a>');
document.writeln('                        </li>');
document.writeln('                    </ul>');
document.writeln('                </div>');
document.writeln('                <div class="item">');
document.writeln('                    <h3>云联万家（北京）网络科技有限公司</h3>');
document.writeln('                    <ul>');
document.writeln('                        <li>地址：北京市朝阳区大屯路安立路6号中科资源大厦7层</li>');
document.writeln('                        <li>电话：010-12345678</li>');
document.writeln('                        <li>邮编：100100</li>');
document.writeln('                    </ul>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('            <div class="pull-right">');
document.writeln('                <div class="erweima">');
document.writeln('                    <img src="../images/common/ma.png" />');
document.writeln('                    <p>手机扫描二维码</p>');
document.writeln('                    <p>下载云联万家APP</p>');
document.writeln('                </div>');
document.writeln('            </div>');
document.writeln('        </div>');
document.writeln('        <div class="footer-bot">');
document.writeln('            <p>');
document.writeln('                <span>@2018云联万家</span>');
document.writeln('                <span>All Rights Reserved</span>');
document.writeln('                <span>云联万家（北京）网络科技有限公司</span>');
document.writeln('                <span>京公网安备11010802012345号</span>');
document.writeln('                <span>京ICP151234号</span>');
document.writeln('                <span>京ICP备13012345号</span>');
document.writeln('            </p>');
document.writeln('        </div>');
document.writeln('    </div>');
document.writeln('</footer>');